/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type WritingPiece = {
  _id: string;
  _type: "writingPiece";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: "Book Review" | "Essay" | "Short Story" | "Opinion";
  externalUrl?: string;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  publishedDate?: string;
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type BrandCollab = {
  _id: string;
  _type: "brandCollab";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  brandLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  collabType?:
    "Sponsored Post" | "Reel" | "Blog Feature" | "Long-term Partnership";
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  testimonialQuote?: string;
  testimonialAuthor?: string;
  resultsOrMetrics?: string;
  projectUrl?: string;
  date?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  platform?: "Instagram" | "YouTube" | "TikTok";
  embedUrl?: string;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  caption?: string;
  publishedDate?: string;
  featured?: boolean;
};

export type BookReview = {
  _id: string;
  _type: "bookReview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  bookTitle?: string;
  author?: string;
  slug?: Slug;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  rating?: 0 | 0.5 | 1 | 1.5 | 2 | 2.5 | 3 | 3.5 | 4 | 4.5 | 5;
  genre?: Array<string>;
  reviewExcerpt?: string;
  fullReview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  affiliateLink?: string;
  associatedReelUrl?: string;
  publishedDate?: string;
  featured?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type About = {
  _id: string;
  _type: "about";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  education?: Array<{
    institution?: string;
    degree?: string;
    year?: string;
    passingYear?:
      | 2000
      | 2001
      | 2002
      | 2003
      | 2004
      | 2005
      | 2006
      | 2007
      | 2008
      | 2009
      | 2010
      | 2011
      | 2012
      | 2013
      | 2014
      | 2015
      | 2016
      | 2017
      | 2018
      | 2019
      | 2020
      | 2021
      | 2022
      | 2023
      | 2024
      | 2025
      | 2026
      | 2027
      | 2028
      | 2029
      | 2030;
    scoreLabel?: string;
    _type: "educationItem";
    _key: string;
  }>;
  skills?: Array<{
    category?: "Writing" | "Research" | "Digital" | "Communication";
    items?: Array<string>;
    _type: "skillCategory";
    _key: string;
  }>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  profileImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialHandles?: Array<{
    platform?:
      | "Instagram"
      | "WordPress"
      | "LinkedIn"
      | "YouTube"
      | "Threads"
      | "TikTok"
      | "Goodreads"
      | "Twitter"
      | "Substack"
      | "Spotify"
      | "Pinterest"
      | "Email";
    url?: string;
    handle?: string;
    _type: "socialLink";
    _key: string;
  }>;
  metrics?: {
    followers?: number;
    avgEngagementRate?: number;
    avgReach?: number;
    monthlyViews?: number;
    lastUpdated?: string;
  };
  resumeFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | WritingPiece
  | SanityImageCrop
  | SanityImageHotspot
  | BrandCollab
  | Post
  | BookReview
  | Slug
  | About
  | SanityFileAssetReference
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {    name,    tagline,    bio,    profileImage,    socialHandles,    metrics,    "resumeUrl": resumeFile.asset->url,    seo  }
export type SiteSettingsQueryResult = {
  name: string | null;
  tagline: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  profileImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  socialHandles: Array<{
    platform?:
      | "Email"
      | "Goodreads"
      | "Instagram"
      | "LinkedIn"
      | "Pinterest"
      | "Spotify"
      | "Substack"
      | "Threads"
      | "TikTok"
      | "Twitter"
      | "WordPress"
      | "YouTube";
    url?: string;
    handle?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
  metrics: {
    followers?: number;
    avgEngagementRate?: number;
    avgReach?: number;
    monthlyViews?: number;
    lastUpdated?: string;
  } | null;
  resumeUrl: string | null;
  seo: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: metricsQuery
// Query: *[_type == "siteSettings"][0].metrics {    followers,    avgEngagementRate,    avgReach,    monthlyViews,    lastUpdated  }
export type MetricsQueryResult = {
  followers: number | null;
  avgEngagementRate: number | null;
  avgReach: number | null;
  monthlyViews: number | null;
  lastUpdated: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: featuredPostsQuery
// Query: *[_type == "post" && featured == true] | order(publishedDate desc) [0...6] {    _id,    title,    platform,    embedUrl,    thumbnail,    caption,    publishedDate,    featured  }
export type FeaturedPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  platform: "Instagram" | "TikTok" | "YouTube" | null;
  embedUrl: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  caption: string | null;
  publishedDate: string | null;
  featured: true;
}>;

// Source: sanity/lib/queries.ts
// Variable: recentPostsQuery
// Query: *[_type == "post"] | order(publishedDate desc) [0...6] {    _id,    title,    platform,    embedUrl,    thumbnail,    caption,    publishedDate,    featured  }
export type RecentPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  platform: "Instagram" | "TikTok" | "YouTube" | null;
  embedUrl: string | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  caption: string | null;
  publishedDate: string | null;
  featured: boolean | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: bookReviewsQuery
// Query: *[_type == "bookReview"] | order(publishedDate desc) {    _id,    bookTitle,    author,    slug,    coverImage,    rating,    genre,    reviewExcerpt,    affiliateLink,    associatedReelUrl,    publishedDate,    featured  }
export type BookReviewsQueryResult = Array<{
  _id: string;
  bookTitle: string | null;
  author: string | null;
  slug: Slug | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  rating: 0.5 | 0 | 1.5 | 1 | 2.5 | 2 | 3.5 | 3 | 4.5 | 4 | 5 | null;
  genre: Array<string> | null;
  reviewExcerpt: string | null;
  affiliateLink: string | null;
  associatedReelUrl: string | null;
  publishedDate: string | null;
  featured: boolean | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: brandCollabsQuery
// Query: *[_type == "brandCollab"] | order(date desc) {    _id,    brandName,    brandLogo,    collabType,    description,    testimonialQuote,    testimonialAuthor,    resultsOrMetrics,    projectUrl,    date  }
export type BrandCollabsQueryResult = Array<{
  _id: string;
  brandName: string | null;
  brandLogo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  collabType:
    "Blog Feature" | "Long-term Partnership" | "Reel" | "Sponsored Post" | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  testimonialQuote: string | null;
  testimonialAuthor: string | null;
  resultsOrMetrics: string | null;
  projectUrl: string | null;
  date: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: writingPiecesQuery
// Query: *[_type == "writingPiece"] | order(publishedDate desc) {    _id,    title,    category,    externalUrl,    excerpt,    coverImage,    publishedDate,    featured  }
export type WritingPiecesQueryResult = Array<{
  _id: string;
  title: string | null;
  category: "Book Review" | "Essay" | "Opinion" | "Short Story" | null;
  externalUrl: string | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedDate: string | null;
  featured: boolean | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: aboutQuery
// Query: *[_type == "about"][0] {    intro,    "education": education[] {      institution,      degree,      year,      passingYear,      scoreLabel    },    skills  }
export type AboutQueryResult = {
  intro: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  education: Array<{
    institution: string | null;
    degree: string | null;
    year: string | null;
    passingYear:
      | 2000
      | 2001
      | 2002
      | 2003
      | 2004
      | 2005
      | 2006
      | 2007
      | 2008
      | 2009
      | 2010
      | 2011
      | 2012
      | 2013
      | 2014
      | 2015
      | 2016
      | 2017
      | 2018
      | 2019
      | 2020
      | 2021
      | 2022
      | 2023
      | 2024
      | 2025
      | 2026
      | 2027
      | 2028
      | 2029
      | 2030
      | null;
    scoreLabel: string | null;
  }> | null;
  skills: Array<{
    category?: "Communication" | "Digital" | "Research" | "Writing";
    items?: Array<string>;
    _type: "skillCategory";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings"][0] {\n    name,\n    tagline,\n    bio,\n    profileImage,\n    socialHandles,\n    metrics,\n    "resumeUrl": resumeFile.asset->url,\n    seo\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "siteSettings"][0].metrics {\n    followers,\n    avgEngagementRate,\n    avgReach,\n    monthlyViews,\n    lastUpdated\n  }\n': MetricsQueryResult;
    '\n  *[_type == "post" && featured == true] | order(publishedDate desc) [0...6] {\n    _id,\n    title,\n    platform,\n    embedUrl,\n    thumbnail,\n    caption,\n    publishedDate,\n    featured\n  }\n': FeaturedPostsQueryResult;
    '\n  *[_type == "post"] | order(publishedDate desc) [0...6] {\n    _id,\n    title,\n    platform,\n    embedUrl,\n    thumbnail,\n    caption,\n    publishedDate,\n    featured\n  }\n': RecentPostsQueryResult;
    '\n  *[_type == "bookReview"] | order(publishedDate desc) {\n    _id,\n    bookTitle,\n    author,\n    slug,\n    coverImage,\n    rating,\n    genre,\n    reviewExcerpt,\n    affiliateLink,\n    associatedReelUrl,\n    publishedDate,\n    featured\n  }\n': BookReviewsQueryResult;
    '\n  *[_type == "brandCollab"] | order(date desc) {\n    _id,\n    brandName,\n    brandLogo,\n    collabType,\n    description,\n    testimonialQuote,\n    testimonialAuthor,\n    resultsOrMetrics,\n    projectUrl,\n    date\n  }\n': BrandCollabsQueryResult;
    '\n  *[_type == "writingPiece"] | order(publishedDate desc) {\n    _id,\n    title,\n    category,\n    externalUrl,\n    excerpt,\n    coverImage,\n    publishedDate,\n    featured\n  }\n': WritingPiecesQueryResult;
    '\n  *[_type == "about"][0] {\n    intro,\n    "education": education[] {\n      institution,\n      degree,\n      year,\n      passingYear,\n      scoreLabel\n    },\n    skills\n  }\n': AboutQueryResult;
  }
}
